name: CI - Back-end

on:
  push:
    branches:
      - "master"
      - "develop"
      - "hotfix/**"
      - "feature/**"
      - "renovate/**"
      - "dependabot/**"
    paths:
      - "backend/**"

jobs:
  build:
    name: CI - Back-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test
